"use strict";
var tr = React.createFactory("tr");
var th = React.createFactory("th");
var td = React.createFactory("td");
var div = React.createFactory("div");
var center = React.createFactory("center");
var button = React.createFactory("button");
var table = React.createFactory("table");
var tbody = React.createFactory("tbody");
var thead = React.createFactory("thead");
var h3 = React.createFactory("h3");
var link = React.createFactory("a");
var br = React.createFactory("br");
var p = React.createFactory("p");
var label = React.createFactory("label");
var input = React.createFactory("input");